name: ar_panorama_app
description: Simple AR Panorama Flutter App

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  panorama_viewer: ^2.0.7
  permission_handler: ^10.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/panorama/